package main

import (
	"log/slog"
	"os"
	"os/signal"
	"strconv"
	"syscall"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	policyv1 "github.com/TooezzE/contracts/gen/go/policy/v1"
	"github.com/TooezzE/gateway/internal/client"
	"github.com/TooezzE/gateway/internal/config"
	"github.com/TooezzE/gateway/internal/handler"
	"github.com/TooezzE/gateway/internal/policy"
	"github.com/TooezzE/gateway/internal/server"
)

const (
	envLocal = "local"
	envProd  = "prod"
)

func main() {
	cfg := config.MustLoad()

	log := setupLogger(cfg.Env)

	log.Info("starting gRPC gateway", slog.String("env", cfg.Env))

	conn, err := grpc.NewClient(
		strconv.Itoa(cfg.GRPC.Port),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		log.Error(err.Error())
		return
	}

	policyGrpcClient := policyv1.NewPolicyServiceClient(conn)
	policyClient := policy.New(policyGrpcClient)

	// Example:
	// init billing client like PaymentServiceClient generated by protobuf
	var paymentClient client.Invoker
	// init other clients...
	var otherClient client.Invoker

	registry := client.New(map[string]client.Invoker{
		"payment-service": client.NewCBInvoker("payment-service", paymentClient),
		"other-service":   client.NewCBInvoker("other-service", otherClient),
	})
	h := handler.New(policyClient, registry)

	server := server.New(log, cfg.GRPC.Port)

	go server.MustRun(h)

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)

	sig := <-stop

	log.Info("received signal, shutting down", slog.String("signal", sig.String()))
	server.Stop()
	log.Info("gRPC server stopped")
}

func setupLogger(env string) *slog.Logger {
	var log *slog.Logger

	switch env {
	case envLocal:
		log = slog.New(
			slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}),
		)
	case envProd:
		log = slog.New(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}),
		)
	}

	return log
}
